planning_task:
  description: >
    Generate a comprehensive, evidence-based content plan for describing {cancer_type} cancer based on advanced WSI analysis methodologies.
    The plan must include:
    - Systematic structure and hierarchical organization for the cancer description
    - Key morphological identification characteristics to be analyzed and documented
    - Visual and architectural features that require detailed description
    - Cellular characteristics and tissue patterns to be evaluated
    - Immunohistochemical markers and molecular features relevant to diagnosis
    - Differential diagnosis considerations and distinguishing features
    - Clinical correlation requirements and prognostic factors
    - Quality assessment criteria and validation checkpoints
    - Expected output specifications and formatting requirements
    - Integration with current pathology guidelines and standards (WHO, CAP, etc.)
  expected_output: >
    A detailed, structured content plan in markdown format containing:
    - Executive summary of the cancer type with epidemiological context
    - Comprehensive outline with main sections, subsections, and detailed specifications
    - Morphological identification characteristics framework with specific criteria
    - Visual feature analysis guidelines with magnification and staining specifications
    - Cellular architecture evaluation parameters and measurement standards
    - Immunohistochemical panel recommendations and interpretation guidelines
    - Differential diagnosis matrix with distinguishing features
    - Clinical correlation requirements and prognostic factor integration
    - Quality assessment criteria and validation protocols
    - Document length specifications, formatting requirements, and publication standards
  agent: planning_agent

description_generation_task:
  description: >
    Based on the comprehensive plan from the planning agent, generate detailed, medically accurate descriptions for {cancer_type} cancer 
    using advanced WSI analysis expertise. Focus specifically on:
    - Morphological identification characteristics: detailed cellular morphology, nuclear features, cytoplasmic characteristics, 
      and architectural patterns visible in WSI analysis
    - Visual and architectural features: comprehensive description of tissue organization, growth patterns, stromal interactions, 
      and spatial relationships as observed in whole slide images
    - Cellular characteristics: nuclear-to-cytoplasmic ratios, mitotic activity, cellular pleomorphism, and differentiation patterns
    - Tissue architecture: glandular formation, solid growth patterns, papillary structures, and infiltrative patterns
    - Diagnostic markers: specific morphological features that aid in definitive diagnosis
    - Immunohistochemical correlations: relationship between morphology and molecular markers
    - Histopathological grading: integration of morphological features with established grading systems
    - Vascular and lymphatic involvement: assessment of invasion patterns and metastatic potential
    - Clinical significance: correlation between morphological findings and clinical outcomes
    Utilize the comprehensive knowledge base to ensure medical accuracy, current guideline compliance, and completeness.
  expected_output: >
    A comprehensive, medically accurate description document containing:
    - Detailed morphological identification characteristics section with specific cellular and architectural features
    - Visual and architectural features section with comprehensive WSI-specific descriptions including magnification references
    - Cellular characteristics analysis with quantitative and qualitative assessments
    - Tissue architecture description with pattern recognition and classification
    - Histopathological markers and diagnostic features with clinical correlation
    - Immunohistochemical profile and molecular marker correlations
    - Differential diagnosis considerations with distinguishing morphological features
    - Clinical significance and prognostic implications based on morphological findings
    - Grading and staging correlations where applicable
    - Structured in clear, professional medical language with appropriate terminology
    - Formatted as markdown with proper headers, subheaders, and medical documentation standards
  agent: description_generator

description_evaluation_task:
  description: >
    Perform comprehensive medical review and validation of the cancer description generated by the description generator agent. 
    Conduct systematic evaluation including:
    - Medical accuracy verification: validate all morphological descriptions against current pathology literature and guidelines
    - Completeness assessment: ensure all required sections from the original plan are thoroughly addressed
    - Terminology consistency: verify proper usage of standardized medical terminology and pathology nomenclature
    - Clarity and readability: assess professional language usage and comprehensibility for medical professionals
    - Guideline compliance: verify adherence to WHO, CAP, and other relevant international pathology standards
    - Diagnostic accuracy: validate that morphological descriptions support accurate diagnostic conclusions
    - Content quality assessment: identify weak, unclear, or insufficiently detailed sections
    - Consistency verification: ensure uniform approach and terminology throughout the document
    - Gap identification: detect missing critical information or inadequate coverage of important features
    - Reference validation: verify that all morphological descriptions are evidence-based and current
    Remove or significantly improve any content that does not meet professional medical standards.
  expected_output: >
    A rigorously validated, cleaned-up markdown document with:
    - All medical inaccuracies corrected or clearly flagged for expert review
    - Weak, unclear, or insufficiently detailed sections removed or substantially improved
    - Consistent, professional medical terminology throughout
    - Clear, logical organization that follows evidence-based pathology reporting standards
    - Comprehensive coverage of all morphological features relevant to diagnosis
    - Proper integration of clinical correlations and prognostic factors
    - Detailed comments on significant changes made during the review process
    - Quality assessment summary with specific metrics and validation criteria
    - Compliance verification with international pathology guidelines
    - Recommendations for any additional content or modifications needed
  agent: description_evaluator

finalization_task:
  description: >
    Transform the validated cancer description into a professional, publication-ready medical document that meets the highest 
    standards of medical documentation and scientific publishing, AND produce a structured JSON representation of the key morphological features for each cancer type. Execute comprehensive formatting, organization, and data-export tasks including:
    - Professional document structure: implement standardized medical document hierarchy and organization
    - Consistent markdown formatting: apply proper syntax, headers, subheaders, and formatting elements
    - Medical documentation standards: ensure compliance with clinical documentation and pathology reporting guidelines
    - Reference integration: add appropriate citations and reference formatting where needed
    - Document metadata: include comprehensive document information, creation details, and version control
    - Quality assurance formatting: implement final formatting checks and consistency verification
    - Publishing preparation: ensure document meets standards for medical education, clinical reference, and publication
    - Accessibility optimization: structure document for easy navigation and reference
    - Professional presentation: create a polished, professional appearance suitable for medical environments
    - Version control: implement proper document versioning and change tracking
    - Structured data export: construct a valid JSON object where each cancer type key maps to an array of concise morphological feature statements (as many distinct statements as possible), following the prefix format (e.g., "ccRCC  statement") and UTF-8 JSON standards
  expected_output: >
    Two outputs:
    1. A professionally formatted, publication-ready markdown document (.md) containing:
       - Properly structured headers and hierarchical organization with clear navigation
       - Consistent, professional formatting throughout with appropriate use of markdown elements
       - Complete document metadata including title, authors, creation date, version, and purpose
       - Professional medical document structure suitable for clinical and educational use
       - All content validated, finalized, and ready for integration into medical systems
       - Proper formatting of tables, lists, and structured content where applicable
       - Clear section demarcation and logical flow for easy reference and navigation
       - Professional typography and spacing appropriate for medical documentation
       - Citation placeholders and reference formatting where applicable
       - Quality assurance summary confirming final document meets all specified standards
       - Version control information and change log summary
       - Ready for deployment in medical education, clinical reference, or publication contexts
    2. A valid JSON object where:
       - Each key is the full cancer type name with abbreviation in parentheses
       - Each value is an array (no upper bound) of strings, each beginning with the abbreviation followed by two spaces and a concise morphological feature statement
       - The JSON is syntactically valid (UTF-8, double-quoted keys/values, no comments) and ready for storage or direct consumption by downstream applications
  agent: finalizer_agent
