planning_task:
  description: >
    Generate a comprehensive, evidence-based content plan for describing {cancer_type} cancer based on advanced WSI analysis methodologies.
    The plan must include:
    - Systematic structure and hierarchical organization for the cancer description
    - Key morphological identification characteristics to be analyzed and documented
    - Visual and architectural features that require detailed description
    - Cellular characteristics and tissue patterns to be evaluated
    - Immunohistochemical markers and molecular features relevant to diagnosis
    - Differential diagnosis considerations and distinguishing features
    - Clinical correlation requirements and prognostic factors
    - Quality assessment criteria and validation checkpoints
    - Expected output specifications and formatting requirements
    - Integration with current pathology guidelines and standards (WHO, CAP, etc.)
  expected_output: >
    A detailed, structured content plan in markdown format containing:
    - Executive summary of the cancer type with epidemiological context
    - Comprehensive outline with main sections, subsections, and detailed specifications
    - Morphological identification characteristics framework with specific criteria
    - Visual feature analysis guidelines with magnification and staining specifications
    - Cellular architecture evaluation parameters and measurement standards
    - Immunohistochemical panel recommendations and interpretation guidelines
    - Differential diagnosis matrix with distinguishing features
    - Clinical correlation requirements and prognostic factor integration
    - Quality assessment criteria and validation protocols
    - Document length specifications, formatting requirements, and publication standards
  agent: planning_agent

description_generation_task:
  description: >
    Based on the comprehensive plan from the planning agent, generate detailed, medically accurate descriptions for {cancer_type} cancer 
    using advanced WSI analysis expertise. Focus specifically on:
    - Morphological identification characteristics: detailed cellular morphology, nuclear features, cytoplasmic characteristics, 
      and architectural patterns visible in WSI analysis
    - Visual and architectural features: comprehensive description of tissue organization, growth patterns, stromal interactions, 
      and spatial relationships as observed in whole slide images
    - Cellular characteristics: nuclear-to-cytoplasmic ratios, mitotic activity, cellular pleomorphism, and differentiation patterns
    - Tissue architecture: glandular formation, solid growth patterns, papillary structures, and infiltrative patterns
    - Diagnostic markers: specific morphological features that aid in definitive diagnosis
    - Immunohistochemical correlations: relationship between morphology and molecular markers
    - Histopathological grading: integration of morphological features with established grading systems
    - Vascular and lymphatic involvement: assessment of invasion patterns and metastatic potential
    - Clinical significance: correlation between morphological findings and clinical outcomes
    Utilize the comprehensive knowledge base to ensure medical accuracy, current guideline compliance, and completeness.
  expected_output: >
    A comprehensive, medically accurate description document containing:
    - Detailed morphological identification characteristics section with specific cellular and architectural features
    - Visual and architectural features section with comprehensive WSI-specific descriptions including magnification references
    - Cellular characteristics analysis with quantitative and qualitative assessments
    - Tissue architecture description with pattern recognition and classification
    - Histopathological markers and diagnostic features with clinical correlation
    - Immunohistochemical profile and molecular marker correlations
    - Differential diagnosis considerations with distinguishing morphological features
    - Clinical significance and prognostic implications based on morphological findings
    - Grading and staging correlations where applicable
    - Structured in clear, professional medical language with appropriate terminology
    - Formatted as markdown with proper headers, subheaders, and medical documentation standards
  agent: description_generator

description_evaluation_task:
  description: >
    Perform comprehensive medical review and validation of the cancer description generated by the description generator agent. 
    Conduct systematic evaluation including:
    - Medical accuracy verification: validate all morphological descriptions against current pathology literature and guidelines
    - Completeness assessment: ensure all required sections from the original plan are thoroughly addressed
    - Terminology consistency: verify proper usage of standardized medical terminology and pathology nomenclature
    - Clarity and readability: assess professional language usage and comprehensibility for medical professionals
    - Guideline compliance: verify adherence to WHO, CAP, and other relevant international pathology standards
    - Diagnostic accuracy: validate that morphological descriptions support accurate diagnostic conclusions
    - Content quality assessment: identify weak, unclear, or insufficiently detailed sections
    - Consistency verification: ensure uniform approach and terminology throughout the document
    - Gap identification: detect missing critical information or inadequate coverage of important features
    - Reference validation: verify that all morphological descriptions are evidence-based and current
    Remove or significantly improve any content that does not meet professional medical standards.
  expected_output: >
    A rigorously validated, cleaned-up markdown document with:
    - All medical inaccuracies corrected or clearly flagged for expert review
    - Weak, unclear, or insufficiently detailed sections removed or substantially improved
    - Consistent, professional medical terminology throughout
    - Clear, logical organization that follows evidence-based pathology reporting standards
    - Comprehensive coverage of all morphological features relevant to diagnosis
    - Proper integration of clinical correlations and prognostic factors
    - Detailed comments on significant changes made during the review process
    - Quality assessment summary with specific metrics and validation criteria
    - Compliance verification with international pathology guidelines
    - Recommendations for any additional content or modifications needed
  agent: description_evaluator

finalization_task:
  description: >
    Produce a concise dictionary-of-list JSON summary for the validated {cancer_type} description.
    Requirements:
    - Focus exclusively on ONE cancer type – {cancer_type} – and summarise findings for each individual whole-slide image (WSI) supplied as input.
    - The output must be a single-level JSON object.
    - Each key is the identifier (e.g., filename or UID) of an input WSI.
    - Each value is an array (5–15 items) of short, clinically relevant sentences that cover macroscopic appearance, microscopic morphology, key molecular/pathogenetic events, and typical clinical presentation for that WSI.
    - Sentences MUST:
        • Start with a capital letter and end with a period.
        • Be plain text (no markdown, list markers, or nested objects).
        • Avoid redundancy and be ≤ 25 words each.
    - Order sentences logically (macroscopic → microscopic → molecular → clinical).
    - Ensure strictly valid JSON: UTF-8, double-quoted keys/strings, no trailing commas, no comments.
  expected_output: >
    A valid JSON object in the requested dictionary-of-list format, for example:
    {
      "case123.svs": [
        "The tumour appears as a yellow-tan mass on gross examination.",
        "Microscopically, tumour cells display clear cytoplasm with delicate vasculature.",
        "Loss of the VHL gene constitutes the key pathogenetic event in this neoplasm.",
        "Stabilisation of HIF subsequently up-regulates VEGF and PDGF signalling pathways.",
        "Patients often present with hematuria, flank pain, and occasionally a palpable mass."
      ]
    }
  agent: finalizer_agent
